# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WLNI_Wijesinghe-COBSCCOMP192P-029' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WLNI_Wijesinghe-COBSCCOMP192P-029
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end
